language: node_js
node_js:
  - "8"
dist: trusty
sudo: required
cache: apt
before_install:
  - sudo curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - sudo apt-get install -y nodejs
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - cask
env:
  - EVM_EMACS=emacs-25.2-travis
install:
  - cask install
script:
  - ./run-lint.sh
  - ./run-tests.sh
